# Generated by Django 3.0.4 on 2020-03-15 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TpsCylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dts_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tps_cylinder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tps_cylinder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DtsCylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True)),
                ('weight', models.IntegerField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dts_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_cylinder', to=settings.AUTH_USER_MODEL)),
                ('tps_cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tps_cylinder', to='common.TpsCylinder')),
            ],
            options={
                'db_table': 'dts_cylinder',
                'ordering': ['weight'],
            },
        ),
    ]
