# Generated by Django 3.0.4 on 2020-03-16 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtscylinder',
            name='dts_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_cylinder_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dtscylinder',
            name='size',
            field=models.CharField(error_messages={'unique': 'Existe un cilindro con el mismo nombre'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tpscylinder',
            name='dts_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tps_cylinder_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tpscylinder',
            name='name',
            field=models.CharField(error_messages={'unique': 'Existe un tipo de cilindro con el mismo nombre'}, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DtsPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(error_messages={'unique': 'Existe una persona con el mismo número de dni'}, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('second_surname', models.CharField(max_length=30)),
                ('sex', models.IntegerField(choices=[(1, 'Memenine'), (2, 'Male')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dts_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_person_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dts_person',
                'ordering': ['dni'],
            },
        ),
        migrations.CreateModel(
            name='DtsCylinderPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dts_cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_cylinder', to='common.DtsCylinder')),
                ('dts_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_person', to='common.DtsPerson')),
                ('dts_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_cylinder_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
